# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_compon.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_version_extractor_by_alexe1ka(object):
    def setupUi(self, version_extractor_by_alexe1ka):
        version_extractor_by_alexe1ka.setObjectName("version_extractor_by_alexe1ka")
        version_extractor_by_alexe1ka.resize(820, 601)
        version_extractor_by_alexe1ka.setMinimumSize(QtCore.QSize(820, 601))
        self.central_widget = QtWidgets.QWidget(version_extractor_by_alexe1ka)
        self.central_widget.setMinimumSize(QtCore.QSize(820, 581))
        self.central_widget.setObjectName("central_widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.central_widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.leftCatalogLayout = QtWidgets.QVBoxLayout()
        self.leftCatalogLayout.setObjectName("leftCatalogLayout")
        self.catalogTreeView = QtWidgets.QTreeView(self.central_widget)
        self.catalogTreeView.setObjectName("catalogTreeView")
        self.leftCatalogLayout.addWidget(self.catalogTreeView)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.progressBar = QtWidgets.QProgressBar(self.central_widget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.count_files_label = QtWidgets.QLabel(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.count_files_label.sizePolicy().hasHeightForWidth())
        self.count_files_label.setSizePolicy(sizePolicy)
        self.count_files_label.setMinimumSize(QtCore.QSize(70, 0))
        self.count_files_label.setText("")
        self.count_files_label.setObjectName("count_files_label")
        self.horizontalLayout.addWidget(self.count_files_label)
        self.leftCatalogLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.leftCatalogLayout)
        self.central_catalog_files_layout = QtWidgets.QVBoxLayout()
        self.central_catalog_files_layout.setObjectName("central_catalog_files_layout")
        self.currentCatalogFilesList = QtWidgets.QListView(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentCatalogFilesList.sizePolicy().hasHeightForWidth())
        self.currentCatalogFilesList.setSizePolicy(sizePolicy)
        self.currentCatalogFilesList.setMinimumSize(QtCore.QSize(180, 530))
        self.currentCatalogFilesList.setMaximumSize(QtCore.QSize(262, 16777215))
        self.currentCatalogFilesList.setObjectName("currentCatalogFilesList")
        self.central_catalog_files_layout.addWidget(self.currentCatalogFilesList)
        self.central_button_layout = QtWidgets.QHBoxLayout()
        self.central_button_layout.setObjectName("central_button_layout")
        self.selectFileExtension = QtWidgets.QComboBox(self.central_widget)
        self.selectFileExtension.setObjectName("selectFileExtension")
        self.selectFileExtension.addItem("")
        self.selectFileExtension.addItem("")
        self.selectFileExtension.addItem("")
        self.selectFileExtension.addItem("")
        self.selectFileExtension.addItem("")
        self.central_button_layout.addWidget(self.selectFileExtension)
        self.startSearchingButton = QtWidgets.QPushButton(self.central_widget)
        self.startSearchingButton.setObjectName("startSearchingButton")
        self.central_button_layout.addWidget(self.startSearchingButton)
        self.central_catalog_files_layout.addLayout(self.central_button_layout)
        self.horizontalLayout_2.addLayout(self.central_catalog_files_layout)
        self.right_result_layoyt = QtWidgets.QVBoxLayout()
        self.right_result_layoyt.setObjectName("right_result_layoyt")
        self.foundHdlFilesListView = QtWidgets.QListView(self.central_widget)
        self.foundHdlFilesListView.setObjectName("foundHdlFilesListView")
        self.right_result_layoyt.addWidget(self.foundHdlFilesListView)
        self.generateReportButton = QtWidgets.QPushButton(self.central_widget)
        self.generateReportButton.setObjectName("generateReportButton")
        self.right_result_layoyt.addWidget(self.generateReportButton)
        self.horizontalLayout_2.addLayout(self.right_result_layoyt)
        version_extractor_by_alexe1ka.setCentralWidget(self.central_widget)

        self.retranslateUi(version_extractor_by_alexe1ka)
        QtCore.QMetaObject.connectSlotsByName(version_extractor_by_alexe1ka)

    def retranslateUi(self, version_extractor_by_alexe1ka):
        _translate = QtCore.QCoreApplication.translate
        version_extractor_by_alexe1ka.setWindowTitle(_translate("version_extractor_by_alexe1ka", "VersionExtractorByAlexe1ka"))
        self.selectFileExtension.setItemText(0, _translate("version_extractor_by_alexe1ka", "*.v"))
        self.selectFileExtension.setItemText(1, _translate("version_extractor_by_alexe1ka", "*.vhd"))
        self.selectFileExtension.setItemText(2, _translate("version_extractor_by_alexe1ka", "*.v/ *.vhd"))
        self.selectFileExtension.setItemText(3, _translate("version_extractor_by_alexe1ka", "*.c/*.cpp,*.h/*.hpp"))
        self.selectFileExtension.setItemText(4, _translate("version_extractor_by_alexe1ka", "*.s/*.asm"))
        self.startSearchingButton.setText(_translate("version_extractor_by_alexe1ka", "Search hdl files"))
        self.generateReportButton.setText(_translate("version_extractor_by_alexe1ka", "Generate report"))

